export interface ContactResI {
  message: string;
  error?: string;
}

// Generated by https://quicktype.io

export interface IPOverview {
  status:      string;
  country:     string;
  countryCode: string;
  region:      string;
  regionName:  string;
  city:        string;
  zip:         string;
  lat:         number;
  lon:         number;
  timezone:    string;
  isp:         string;
  org:         string;
  as:          string;
  query:       string;
}
